env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - standard
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  no-await-in-loop: 0
  semi: [2, "always"]
